### ISSUE TITLE
Edit Users

### ISSUE THREAD

**Issue by HyperLS** [powercord-community/suggestions#121]
**Edit Users**
Allows you to change the icon, name, tag and color of users.

**r-click menu option**
Right Click The User And Add An Option Like "Edit User" Or something

**Based On Better Discord Plugin https://betterdiscordlibrary.com/plugins/Edit%20Users**

----

 - [✔️] I checked if this request wasn't already proposed
 - [✔️] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
@Bowser65 is this something against ToS? Sounds a bit sketch to me as you can literally force someone to look like someone else but I'm not sure. I know a lot of this is doable with css as well.

**Comment by Bowser65** [comment]
For that matter it's already a no-skill-required inspect element trick quite literally anyone can do, so I don't think it can be considered as heavily malicious.

**Comment by ilikepotatoes121** [comment]
seems like an invasion of intellectual property to me, but idk

**Comment by CodingKanin** [comment]
I've seen css snippets that do this exact thing, is a plugin really needed for it?

**Comment by CodingKanin** [comment]
e.g (https://canary.discordapp.com/channels/538759280057122817/542864483543023646/705070946498904105)
```css
[src*="avatars/<USERID>"] ~ .header-23xsNx > .username-1A8OIy {
    font-size: 0;
}
[src*="avatars/<USERID>"] ~ .header-23xsNx > .username-1A8OIy::before {
    content: "Name here";
    font-size: 16px;
}

```
