### ISSUE TITLE
Offline discord 

### ISSUE THREAD

**Issue by imadtg** [powercord-community/suggestions#226]
### Description
i don't know of a better name of it. but it would be a plugin that would let you see chats and messages and DMs when you go offline instead of giving you that rolling discord icon just like the discord phone app

### More info
i don't know how you would go about making this though. probably edit what discord does when you go offline and replace it with a bar on top saying you're offline instead. if you know of a better way to do this then please do.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by BenSegal855** [comment]
For clarification, by "go offline" you mean when your device looses internet connectivity or when you select offline as your status?

**Comment by imadtg** [comment]
i mean when you lose internet connection.

**Comment by Bowser65** [comment]
```css
.container-16j22k {
  display: none !important;
}
```

**Comment by imadtg** [comment]
would be better if it gave an indicator that you went offline too and not just remove that black screen and rotating icon.

**Comment by mrrobboss** [comment]
i can make a snippet for that. my internet is down 99% of the day anyway :keuch:

**Comment by Bowser65** [comment]
```css
.container-16j22k {
  background: transparent;
  pointer-events: none;
}

.container-16j22k * {
  display: none;
}

.container-16j22k::before {
  content: 'You\'ve gone offline';
  display: block;
  bottom: 24px;
  right: 24px;
  position: absolute;
  padding: 8px 16px;
  background-color: #f04747;
  border-radius: 4px;
  color: #fff;
}
```
