### ISSUE TITLE
Delete blocked message

### ISSUE THREAD

**Issue by JustFoxx** [powercord-community/suggestions#255]
Invisible message from blocked members

**Comment by BenSegal855** [comment]
This can be done with this css snippet made by Bowser. In the future, please use the request template as it helps keep requests uniform and gives valuable information to potential plugin developers. 

```css
/*Hide Blocked Messages*/
.wrapper-2a6GCs[data-is-blocked="true"] {
  display: none;
}
```
