### ISSUE TITLE
PowerBorder for Powercord!

### ISSUE THREAD

**Issue by pugthelouie** [powercord-community/suggestions#34]
**Describe the plugin**
PowerBorder would add an animated border to the edges of the discord window that gradually changes color in a gradient style. The concept is taken from the popular terminal app, Hyper.

**Expected behavior**
When enabled, the window should resize a bit and show the border around Discord. It would look a bit like this:

![image](https://user-images.githubusercontent.com/16177268/68357332-fc140200-00e2-11ea-8a7d-bd2bc3d72cd2.png)

Also, if possible, the settings could closely match the settings of the original [HyperBorder](https://github.com/thediaval/hyperborder-elevated). These settings would include width, color hexes, border circle radius, etc...

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by pugthelouie** [comment]
I'll be spearheading this project on my personal repo real soon!

**Comment by dnglchlk** [comment]
Has this been given up on?

**Comment by doggybootsy** [comment]
> Has this been given up on?

I'm pretty sure css can do this its just not pretty

**Comment by doggybootsy** [comment]
```css
:root{
  --Thickness:5px;
  --Speed:10s;
}

.appMount-3lHmkl{
  margin:var(--Thickness);
  width:calc(100% - calc(var(--Thickness) * 2))!important;
  height:calc(100% - calc(var(--Thickness) * 2))!important;
}
.platform-osx .appMount-3lHmkl{
  border-radius:4px;
}
body{
    background-image: linear-gradient(to left, #6666ff, #0099ff , #00ff00, #ff3399, #6666ff);
    animation: gradient-border var(--Speed) linear infinite;
    background-size: 400% 100%;
    color: transparent !important;
}
@keyframes gradient-border {
    0%, 200% {
        background-position: 0 0;
    }

    99.999999999999999% {
        background-position: 130% 0;
    }
}
```
A quick bit of css i made, change the root for the speed and thickness
