### ISSUE TITLE
Hide "State Discovery" tab in Discord's Home page

### ISSUE THREAD

**Issue by RayDeeUx** [powercord-community/suggestions#462]
### Description
Hides the "State Discovery" tab without having to access Discord Experiments.

### More info
None needed.

----

 - [ x ] I checked if this request wasn't already proposed
 - [ x ] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This can be done just using CSS:
```css
.privateChannels-1nO12o .channel-2QD9_O[href='/discovery'] {
	display: none;
}
```
