### ISSUE TITLE
Legible twemoji

### ISSUE THREAD

**Issue by asportnoy** [powercord-community/suggestions#743]
### Description
Replace the all-black emojis with a white version so they're easier to see. An outline could also work but I think just white would look better.

### More info
Some examples: ➕➖➗✖️©️™️®️💲🟰

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by DracoClaw** [comment]
you can do that with CSS. Something like 
```css
img[src="/assets/9a43e631d506ae4818ecefc825dc02ad.svg"], /*heavy_plus_sign*/
img[src="/assets/13c8662cff8e029799a35878b56e23eb.svg"], /*heavy_minus_sign*/
img[src="/assets/e37bc714ecd911af7c558f5aaa0c4464.svg"], /*ant*/
img[src="/assets/d6e12f410c99374f88879450daaaced9.svg"], /*spider*/
img[src="/assets/a784784c984905c2a74507d57aa3523e.svg"], /*black_cat*/
img[src="/assets/f34c63197816c3e60bea4a9537c5fffa.svg"], /*telephone_receiver*/
img[src="/assets/05a1abc6388a96e2a536650433c12fca.svg"], /*video_camera*/
img[src="/assets/f1426431eb7c60fb8c072f90acb07ceb.svg"], /*video_game*/
img[src="/assets/733a0db94b390b2fd5da87408285a079.svg"], /*movie_camera*/
img[src="/assets/654212b1a4cdf391b4a8bb37faf7d18c.svg"], /*projector*/
img[src="/assets/16520d89e684777eedd536346015e71f.svg"], /*electric_plug*/
img[src="/assets/22bbea32f8826e963038329aee825bc1.svg"], /*chess_pawn*/
img[src="/assets/1d2dc7d83ed3182e3348d4f216c15c87.svg"], /*eight_pointed_black_star*/
img[src="/assets/3d663bbe9d97bc976c24ec4d125fe2b3.svg"], /*heavy_division_sign*/
img[src="/assets/133b77ff9fc321682fed3cde12d6355c.svg"], /*heavy_multiplication_x*/
img[src="/assets/1679bb713b6a99e6ddf111d45400be3a.svg"], /*heavy_dollar_sign*/
img[src="/assets/da56d5c7e4409c0c1640ff6ba21ec1ad.svg"], /*currency_exchange*/
img[src="/assets/502afa9807a8da920a357e25c14da10a.svg"], /*wavy_dash*/
img[src="/assets/48c9c24b660f8c392a56f8d28c86f1c3.svg"], /*curly_loop*/
img[src="/assets/6a86f8cca40da89386aa7e9eca926da7.svg"], /*end*/
img[src="/assets/6c928e43c553124e23e45c31c6ddbece.svg"], /*back*/
img[src="/assets/b8b439115436db0c0bbff081749a1ddb.svg"], /*on*/
img[src="/assets/fa259978fede6539d40db4b59a2b0f66.svg"], /*top*/
img[src="/assets/b3f45308df051ef73d8cf63ffe0976c3.svg"], /*soon*/
img[src="/assets/7b3ff12d16d96ca77345da9450986dc7.svg"], /*heavy_check_mark*/
img[src="/assets/6278365424fa5701d3b185e2d9fe8225.svg"], /*black_circle*/
img[src="/assets/60c5854fe77ca7a4946b7c801c559f4a.svg"], /*black_small_square*/
img[src="/assets/7d4f02f7354aee0b30e7e5a35579fff4.svg"], /*black_medium_small_square*/
img[src="/assets/b6a3073e1281d1ef79d48ef130c183b2.svg"], /*black_medium_square*/
img[src="/assets/d0e23cdf2386056cc64e775a6248ed17.svg"], /*black_large_square*/
img[src="/assets/3fe9fcacdbee990bd0d873135689bd5b.svg"], /*spades*/
img[src="/assets/b67a375a6b8f5caeacff463835c44011.svg"], /*clubs*/
img[src="/assets/d91cb297561a6bc50f8c6918d428bc61.svg"],  /*black_heart*/
img[src="/assets/31ef50db484eb3d4b2fbebb4e91a0764.svg"],  /*bomb*/
img[src="https://twemoji.maxcdn.com/v/13.0.2/72x72/2122.png"],  /*tm*/
img[src="https://twemoji.maxcdn.com/v/13.0.2/72x72/a9.png"],  /*copyright*/
img[src="https://twemoji.maxcdn.com/v/13.0.2/72x72/ae.png"]  /*registered*/{
filter: contrast(110%);
}
```
